<div class="nav">

  <div> <a class="home" href="index.shtml"> <img src="images/home.svg" style="height: 2rem;" alt="Homepage"> </a></div>
  <div> <a href="projects.shtml"> Projects </a></div>
  <div class="before"> <a href="contactme.shtml"> Contact Me </a></div>
  <div class="after"> <a href="contactme.shtml"> Contact </a></div>
  <div class="before"> <a href="aboutme.shtml"> About Me </a></div>
  <div class="after"> <a href="aboutme.shtml"> About </a></div>
  <div> <a href="blog.shtml"> Blog </a></div>
  <div id="filler"></div>
  <div id="welcomeback"></div>

</div>
