
<div class="row header">
  <div class="col-5 title">
    <a href="index.shtml"> Boondock Bill's </a>
  </div>
  <div class="col nav">
    <button type="button" class="btn" onClick="window.location.href='aboutus.shtml'"> About Us </button>
    <button type="button" class="btn" onClick="window.location.href='food.shtml'"> Food </button>
    <button type="button" class="btn" onClick="window.location.href='drinks.shtml'"> Drinks </button>
    <button type="button" class="btn" onClick="window.location.href='contactus.shtml'"> Contact Us </button>
  </div>
  </div>
